version: 2
models:
  - name: dim_customer
    columns:
      - name: customer_id
        tests: [unique, not_null]
  - name: dim_product
    columns:
      - name: sku
        tests: [unique, not_null]
  - name: fact_sales
    columns:
      - name: invoice_id
        tests: [not_null]
      - name: customer_id
        tests:
          - relationships:
              to: ref('dim_customer')
              field: customer_id
      - name: sku
        tests:
          - relationships:
              to: ref('dim_product')
              field: sku
